# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Root\Desktop\Projects\OTBD\Algorithm\interface_ui\ui_OTBD.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1436, 1010)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Result = QtWidgets.QWidget()
        self.Result.setObjectName("Result")
        self.treeView = QtWidgets.QTreeView(self.Result)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 1411, 911))
        self.treeView.setObjectName("treeView")
        self.treeView.header().setSortIndicatorShown(True)
        self.comboBox_3 = QtWidgets.QComboBox(self.Result)
        self.comboBox_3.setGeometry(QtCore.QRect(1228, 919, 171, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_2 = QtWidgets.QLabel(self.Result)
        self.label_2.setGeometry(QtCore.QRect(1100, 920, 121, 20))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.Result, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 1411, 871))
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setSortIndicatorShown(True)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 880, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 910, 111, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(1196, 880, 211, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(1070, 880, 111, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(140, 880, 101, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(250, 880, 391, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(650, 880, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 910, 111, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 910, 111, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Test_1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Test_2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Xcomp"))
        self.label_2.setText(_translate("MainWindow", "Приоритетный список"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Result), _translate("MainWindow", "Результирующая таблица"))
        self.pushButton.setText(_translate("MainWindow", "Добавить строку"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить строку"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Test_1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Test_2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Xcomp"))
        self.pushButton_3.setText(_translate("MainWindow", "Отобразить список"))
        self.label.setText(_translate("MainWindow", "Текстовый фильтр"))
        self.pushButton_4.setText(_translate("MainWindow", "Объеденить строки"))
        self.pushButton_5.setText(_translate("MainWindow", "Снять флаги"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Пользовательские списки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
